// src/client/react/form.tsx
/*
 * @adonisjs/inertia
 *
 * (c) AdonisJS
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import React from 'react'
import { Form as InertiaForm } from '@inertiajs/react'

import { useTuyau } from './context.tsx'
import { buildRouteUrl } from '../common.ts'
import type { ExtractRouteBody, RouteParams, Routes } from '../types.ts'

/**
 * Parameters required for route navigation with proper type safety.
 */
export type FormParams<Route extends keyof Routes> = RouteParams<Route>

/**
 * Props of the bundled Inertia Form component, keyed by the form-data shape.
 * `ComponentPropsWithoutRef<typeof InertiaForm>` cannot be used here:
 * inferring props from the generic call signature erases `TForm` to its bare
 * constraint instead of applying the given form-data type, which collapses
 * the render prop's `errors` to `{}`. The instantiation expression applies
 * the form-data type eagerly.
 */
type InertiaFormProps<FormData extends object = Record<string, any>> = Omit<
  Parameters<typeof InertiaForm<FormData>>[0],
  'ref'
>

/**
 * Slot props received by the children render prop, keyed by the form-data
 * shape. In route mode the form-data shape is the route's declared body; in
 * action mode it is the explicit `Form` generic.
 */
export type FormSlotProps<FormData extends object = Record<string, any>> = Parameters<
  Extract<Parameters<typeof InertiaForm<FormData>>[0]['children'], (...args: any[]) => any>
>[0]

/**
 * Instance exposed on the Form ref.
 */
export type FormRef<FormData extends object = Record<string, any>> =
  NonNullable<Parameters<typeof InertiaForm<FormData>>[0]['ref']> extends React.Ref<infer R>
    ? R
    : never

/**
 * Children accepted by the Form component. Declared directly (rather than
 * carried through `Omit` of a deferred type) so the render prop's parameter
 * stays contextually typed at call sites.
 */
type FormChildren<FormData extends object> =
  | React.ReactNode
  | ((props: FormSlotProps<FormData>) => React.ReactNode)

/**
 * Props for the Form component when using route-based navigation. The
 * form-data shape is derived from the route's declared body type, so the
 * render prop, reset options, transform, and ref are all typed from the
 * route without a manual generic.
 */
export type FormRouteProps<Route extends keyof Routes> = Omit<
  InertiaFormProps<ExtractRouteBody<Route>>,
  'action' | 'method' | 'children'
> &
  FormParams<Route> & {
    action?: never
    children?: FormChildren<ExtractRouteBody<Route>>
  }

/**
 * Props for the Form component when using direct action
 */
export type FormActionProps<FormData extends object = Record<string, any>> = Omit<
  InertiaFormProps<FormData>,
  'route' | 'children'
> & {
  route?: never
  routeParams?: never
  qs?: never
  children?: FormChildren<FormData>
}

/**
 * Union type for Form component props - either route-based or direct action
 */
export type FormProps<
  Route extends keyof Routes = keyof Routes,
  FormData extends object = Record<string, any>,
> = FormRouteProps<Route> | FormActionProps<FormData>

/**
 * Internal Form component implementation with forward ref support.
 * Resolves route parameters and generates the appropriate URL and HTTP method
 * for Inertia form submission when using route-based navigation.
 * Falls back to standard InertiaForm when action is provided directly.
 */
function FormInner<
  Route extends keyof Routes = keyof Routes,
  FormData extends object = Record<string, any>,
>(
  props: FormProps<Route, FormData>,
  ref?: React.ForwardedRef<FormRef<ExtractRouteBody<Route>> | FormRef<FormData>>
) {
  const tuyau = useTuyau()

  // Check if props has action (direct form submission)
  if ('action' in props && props.action !== undefined) {
    /**
     * The spreads are untyped on purpose: the public FormProps surface
     * carries the type safety, while the upstream component would try to
     * re-infer the form-data type from the spread and clash with the outer
     * generic.
     */
    return <InertiaForm {...(props as any)} ref={ref} />
  }

  // Route-based navigation. getRoute resolves the HTTP methods and urlFor
  // builds the URL, serializing query string parameters in one place.
  const {
    route,
    routeParams: params,
    qs,
    method,
    ...formProps
  } = props as FormRouteProps<Route>
  const { methods } = tuyau.getRoute(route, { params })
  const url = buildRouteUrl(tuyau, route, params, qs)

  return (
    <InertiaForm
      {...(formProps as any)}
      action={{ url, method: method ?? (methods[0].toLowerCase() as any) }}
      ref={ref}
    />
  )
}

/**
 * Type-safe Form component for Inertia.js form submissions.
 *
 * Provides compile-time route validation and automatic parameter type checking
 * based on your application's route definitions. Automatically resolves the
 * correct URL and HTTP method for each route. Alternatively, you can use
 * the standard action prop for direct form submission.
 *
 * @example
 * ```tsx
 * // Form to a route without parameters
 * <Form route="users.store">
 *   {({ processing }) => (
 *     <>
 *       <input type="text" name="name" />
 *       <button type="submit" disabled={processing}>Create</button>
 *     </>
 *   )}
 * </Form>
 *
 * // Form to a route with required parameters
 * <Form route="users.update" routeParams={{ id: 1 }}>
 *   {({ errors }) => (
 *     <>
 *       <input type="text" name="name" />
 *       {errors.name && <div>{errors.name}</div>}
 *       <button type="submit">Update</button>
 *     </>
 *   )}
 * </Form>
 *
 * // Form with direct action
 * <Form action={{ url: '/users', method: 'post' }}>
 *   {({ processing }) => (
 *     <>
 *       <input type="text" name="name" />
 *       <button type="submit" disabled={processing}>Create</button>
 *     </>
 *   )}
 * </Form>
 * ```
 */
export const Form: {
  <Route extends keyof Routes>(
    props: FormRouteProps<Route> & {
      ref?: React.Ref<FormRef<ExtractRouteBody<Route>>>
    }
  ): ReturnType<typeof FormInner>
  <FormData extends object = Record<string, any>>(
    props: FormActionProps<FormData> & {
      ref?: React.Ref<FormRef<FormData>>
    }
  ): ReturnType<typeof FormInner>
  /**
   * Combined signature used by component helpers such as React.createElement.
   */
  <Route extends keyof Routes, FormData extends object = Record<string, any>>(
    props:
      | (FormRouteProps<Route> & {
          ref?: React.Ref<FormRef<ExtractRouteBody<Route>>>
        })
      | (FormActionProps<FormData> & {
          ref?: React.Ref<FormRef<FormData>>
        })
  ): ReturnType<typeof FormInner>
} = React.forwardRef(FormInner as any) as any

// src/client/svelte/form.svelte
<!--
  @adonisjs/inertia

  (c) AdonisJS

  For the full copyright and license information, please view the LICENSE
  file that was distributed with this source code.
-->
<!--
  @component
  Type-safe Form component for Inertia.js form submissions.

  Provides compile-time route validation and automatic parameter type
  checking based on your application's route definitions. Automatically
  resolves the correct URL and HTTP method for each route. Alternatively,
  you can use the standard action prop for direct form submission.

  In route mode the form-data shape is derived from the route's declared
  body, so the children snippet (errors, getData, reset, ...) follows the
  route without a manual generic.

  ```svelte
  <Form route="users.store">
    {#snippet children({ processing })}
      <input type="text" name="name" />
      <button type="submit" disabled={processing}>Create</button>
    {/snippet}
  </Form>

  <Form route="users.update" routeParams={{ id: 1 }}>
    {#snippet children({ errors })}
      <input type="text" name="name" />
      {#if errors.name}<div>{errors.name}</div>{/if}
      <button type="submit">Update</button>
    {/snippet}
  </Form>

  <Form action={{ url: '/users', method: 'post' }}>
    {#snippet children({ processing })}
      <input type="text" name="name" />
      <button type="submit" disabled={processing}>Create</button>
    {/snippet}
  </Form>
  ```
-->
<script
  lang="ts"
  generics="Route extends keyof Routes, FormData extends Record<string, any> = FormDataType<ExtractRouteBody<Route>>"
>
  import { Form as InertiaForm } from '@inertiajs/svelte'
  // Inertia's declarations omit NodeNext-compatible extensions from internal type re-exports.
  // prettier-ignore
  // @ts-ignore TypeScript resolves this export correctly in client projects using Bundler resolution.
  import type { FormDataType } from '@inertiajs/core'

  import { buildRouteUrl, useTuyau } from './internals.js'
  import type { ExtractRouteBody, Routes } from '../types.ts'
  import type { FormProps, FormRouteProps } from './types.ts'

  /**
   * `FormData` is a second type parameter rather than only a default on
   * FormProps so action mode stays inferable: with no route to derive the
   * form-data shape from, it is recovered from an annotated `children`
   * snippet parameter instead. Route mode never supplies it and falls to the
   * default, which follows the route's declared body.
   */
  const props: FormProps<Route, FormData> = $props()

  /**
   * Read during initialisation: svelte contexts are only readable while the
   * component is being set up, so this cannot be deferred into the derived
   * below.
   */
  const tuyau = useTuyau()

  /**
   * Forwarded so `bind:this` on the wrapper reaches the upstream form API
   * (submit, reset, setError, ...) instead of the wrapper itself.
   */
  let inner = $state<any>(undefined)

  export const getFormData = (...args: any[]) => inner?.getFormData(...args)
  export const getData = (...args: any[]) => inner?.getData(...args)
  export const submit = (...args: any[]) => inner?.submit(...args)
  export const reset = (...args: any[]) => inner?.reset(...args)
  export const clearErrors = (...args: any[]) => inner?.clearErrors(...args)
  export const resetAndClearErrors = (...args: any[]) => inner?.resetAndClearErrors(...args)
  export const setError = (...args: any[]) => inner?.setError(...args)
  export const defaults = (...args: any[]) => inner?.defaults(...args)
  export const validate = (...args: any[]) => inner?.validate(...args)
  export const valid = (...args: any[]) => inner?.valid(...args)
  export const invalid = (...args: any[]) => inner?.invalid(...args)
  export const touch = (...args: any[]) => inner?.touch(...args)
  export const touched = (...args: any[]) => inner?.touched(...args)
  export const validator = (...args: any[]) => inner?.validator(...args)

  /**
   * Route-based navigation. getRoute resolves the HTTP methods and urlFor
   * builds the URL, serializing query string parameters in one place.
   *
   * The action mode short-circuits: the route bindings are stripped and
   * every remaining prop is forwarded untouched, so a plain form behaves
   * exactly like the upstream component.
   */
  const resolved = $derived.by(() => {
    const { route, routeParams, qs, method, ...formProps } = props as FormRouteProps<Route> & {
      action?: unknown
    }

    if (formProps.action !== undefined) {
      return method === undefined ? formProps : { ...formProps, method }
    }

    const { methods } = tuyau.getRoute(route, { params: routeParams })

    return {
      ...formProps,
      action: {
        url: buildRouteUrl(tuyau, route, routeParams, qs),
        method: method ?? methods[0].toLowerCase(),
      },
    }
  })
</script>

<InertiaForm bind:this={inner} {...resolved} />
